pipeline {
    agent any

    tools {
        nodejs 'NodeJS-20'
    }

    environment {
        DOCKERHUB_USER = '06dewa'
        STUDENT_ID     = '02250349'
    }

    stages {

        stage('Checkout') {
            steps {
                git branch: 'main',
                    url: 'https://github.com/Dechen-0349/Dechen_DSO101_Assignment.git',
                    credentialsId: 'github-creds'
            }
        }

        stage('Install Dependencies') {
            steps {
                dir('A1/backend') {
                    bat 'npm install'
                }
            }
        }

        stage('Test') {
            steps {
                dir('A1/backend') {
                    bat 'npm test'
                }
            }
            post {
                always {
                    junit 'A1/backend/junit.xml'
                }
            }
        }

        stage('Build Docker Images') {
            steps {
                script {
                    docker.build("${DOCKERHUB_USER}/be-todo:${STUDENT_ID}", './A1/backend')
                    docker.build("${DOCKERHUB_USER}/fe-todo:${STUDENT_ID}", './A1/frontend')
                }
            }
        }

        stage('Push to Docker Hub') {
            steps {
                script {
                    docker.withRegistry('https://registry.hub.docker.com', 'docker-hub-creds') {
                        docker.image("${DOCKERHUB_USER}/be-todo:${STUDENT_ID}").push()
                        docker.image("${DOCKERHUB_USER}/fe-todo:${STUDENT_ID}").push()
                    }
                }
            }
        }
    }

    post {
        success {
            echo 'Pipeline completed successfully!'
        }
        failure {
            echo 'Pipeline failed. Check the logs above.'
        }
    }
}